# rustfmt.toml

edition = "2024"
max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
tab_spaces = 4
hard_tabs = false
match_arm_leading_pipes = "Always"
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
